build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:9.1.0
  amd64: ghcr.io/hassio-addons/debian-base:9.1.0
  armv7: ghcr.io/hassio-addons/debian-base:9.1.0
  i386: ghcr.io/hassio-addons/debian-base:9.1.0