version: '3.8'
services:
  homeassistant:
    container_name: homeassistant-test
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - ../:/config/addons/local/cups-server
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "8123:8123"
    privileged: true
    restart: unless-stopped
